Repository AzureAD/microsoft-authentication-library-for-python, pull requests merged in 2021-03, with the labels that each got.

#318 Only trigger CI/CD when a PR is labelled
  .github/workflows/python-package.yml
Labels: fundamentals

#323 Fix typos in docstring
  msal/application.py
Labels: documentation

#333 Support launching browser in WSL Ubuntu 18.04
  msal/oauth2cli/authcode.py
Labels: enhancement
